# Generated by Django 2.0.2 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name hien thi nhe', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user name', max_length=100, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_url',
            field=models.CharField(default='/https://www.spoj.com/PTIT/users/meoconxinhxan/', max_length=100, verbose_name='url'),
        ),
    ]
